const TABLE_SIMBOLS = {
    AR: "ARS",
    BO: "$",
    BR: "BRL",
    CA: "$",
    CL: "$",
    CO: "COP",
    CR: "$",
    DO: "$",
    EC: "$",
    SV: "$",
    EU: "€",
    GT: "$",
    HN: "$",
    MX: "$",
    NI: "$",
    OTHER: "$",
    PA: "$",
    PY: "$",
    PE: "$",
    UK: "GBP",
    US: "$",
    UY: "$",
    // España no sale como opcion de POS en prod avianca.com
    ES: "€",
}